# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14
# Mod Properties
mod_version=1.21.8-0.1.7
maven_group=net.lilfox
archives_base_name=liltweaks
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.131.0+1.21.8
# check these on https://maven.hendrixshen.top
magiclib_version=0.8.722
magiclib_minecraft_version=1.21.8
lil_lib_version=0.1.3