# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
# Mod Properties
mod_version=1.21.1-0.1.7
maven_group=net.lilfox
archives_base_name=liltweaks
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.115.1+1.21.1
# check these on https://maven.hendrixshen.top
magiclib_version=0.8.662
magiclib_minecraft_version=1.21.1